# Generated by Django 5.2.8 on 2025-11-08 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('admin_level', models.IntegerField(default=1)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('privacy_level', models.IntegerField(default=0)),
                ('topics_of_interest', models.JSONField(default=list)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('college_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='ClubLeader',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.student')),
                ('title', models.CharField(max_length=100)),
                ('leader_start_date', models.DateField()),
            ],
            options={
                'db_table': 'club_leaders',
            },
            bases=('core.student',),
        ),
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata', models.JSONField()),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'db_table': 'club_applications',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('categories', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('members_count', models.IntegerField(default=0)),
                ('leaders_count', models.IntegerField(default=0)),
                ('club_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to='core.clubleader')),
            ],
            options={
                'db_table': 'club',
            },
        ),
    ]
