# Generated by Django 5.2.8 on 2025-11-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_announcement_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('payment_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.student')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('student', 'event')},
            },
        ),
    ]
