# Generated by Django 5.2.8 on 2025-11-22 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity_rank', models.IntegerField(default=1)),
                ('target', models.CharField(max_length=50)),
                ('reviewed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.announcement')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags_created', to='core.user')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core.event')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to='core.admin')),
            ],
            options={
                'db_table': 'flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
