# Generated by Django 5.2.8 on 2025-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('IN_PERSON', 'In Person'), ('VIRTUAL', 'Virtual')], default='IN_PERSON', max_length=20),
        ),
    ]
