# Generated by Django 5.2.8 on 2025-11-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
